name: Execute Jekyll2cms Transformation for FristSpiritCMS on master-push
on: 
  push:
    branches: 
      - master

jobs:
  SendDispatchEvent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Trigger the execution of jekyll2cms latest release in the jekyll2cms repository 
      run: |
        curl -X POST https://api.github.com/repos/adessoAG/jekyll2cms/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$DISPATCH_REPO"'" }}'
