name: Execute Jekyll2cms Transformation for FristSpiritCMS on master-push
on: 
  push:
    branches: 
      - master

jobs:
  SendDispatchEvent:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger the execution of jekyll2cms latest release in the jekyll2cms repository 
      run: |
        curl -XPOST \
             -H "Accept: application/vnd.github.everest-preview+json" \
             -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
             --data '{"event_type": "do-trigger-jekyll2cms"}' \
             ${{ secrets.DISPATCH_REPO }}
