name: Execute Jekyll2cms Transformation for FristSpiritCMS on master-push
on: 
  push:
    branches: 
      - master

jobs:
  SendDispatchEvent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Trigger the execution of jekyll2cms latest release in the jekyll2cms repository 
      run: |
        curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/dispatches --data '{"event_type": "build_application"}'
